config/routes.rb
Rails.application.routes.draw do
resources :cocktails do
    resources :doses, only: [:new, :create, :index, :show]
  end
  root to: 'cocktails#index'
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

# Index and show are always together.
# Index is all of the objects
# Show is a single object displayed on a page

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end

# Create and New are always together.
# New is the page that gets called where you create
# a new object.
# Create is the method that is called when you submit
# the form on the new page.

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to new_cocktail_dose_path(@cocktail)
  end

  def new
    @cocktail = Cocktail.new
  end

# The Edit and Update page are always together.
# The edit is the page that is being displayed.
# The Update method is whats being called when
# submitting the page.

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

# Single option destroy which has no partner inside the controller.

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
# Index and show are always together.
# Index is all of the objects
# Show is a single object displayed on a page

def index
  @doses = Dose.all
  @cocktail = Cocktail.find(params[:cocktail_id])
end

def show
  @dose = Dose.find(params[:id])
end

# Create and New are always together.
# New is the page that gets called where you create
# a new object.
# Create is the method that is called when you submit
# the form on the new page.

def create
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose = Dose.new(dose_params)
  @dose.cocktail = Cocktail.find(params[:cocktail_id])
  @dose.save
  redirect_to cocktail_path(@cocktail)
end

def new
  @cocktail = Cocktail.find(params[:cocktail_id])
  @ingredients = Ingredient.all
  @dose = Dose.new
end

def dose_params
  params.require(:dose).permit(:description, :ingredient_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail) do |a| %>
<%= a.label :name %>
<%= a.text_field :name %>
<%= a.submit %>
<% end %>

app/views/cocktails/edit.html.erb
<%= render 'form' %>

app/views/cocktails/index.html.erb
<h1> This is a list of all the Cocktails!</h1>


<% @cocktails.each do |cocktail| %>
<ul>
  <li id='cocktail' class='cocktail-box'>
    <h2><%= cocktail.name %></h2>
    <td><%= link_to "- Show", cocktail %></td>
    <td><%= link_to "- Edit", edit_cocktail_path(cocktail) %></td>
  </li>
</ul>
<% end %>

app/views/cocktails/new.html.erb
<%= render 'form' %>

app/views/cocktails/show.html.erb
<%= @cocktail.name %>
<%= link_to 'show', cocktail_doses_path(@cocktail) %>

app/views/doses/_form.html.erb
# In order to create something it has to go to the create url

<%= form_for [@cocktail, @dose] do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.select :ingredient_id do %>
<% @ingredients.each do |i| -%>
<%= content_tag(:option, i.name, value: i.id) %>
<% end %>
<% end %>
<%= f.submit %>
<% end %>

app/views/doses/index.html.erb
<h1> This is a list of all the Doses!</h1>


<% @doses.each do |dose| %>
<ul>
  <li id='dose' class='dose-box'>
    <h2><%= dose.description %></h2>
    <td><%= link_to "- Show", cocktail_dose_path(@cocktail, dose) %></td>
  </li>
</ul>
<% end %>

app/views/doses/new.html.erb
<%= render 'form' %>

app/views/doses/show.html.erb
<%= @dose.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>

  <%= yield %>

</body>
</html>